import * as functions from 'firebase-functions';
import * as admin from 'firebase-admin';
import * as PDFDocument from 'pdfkit';
import * as https from 'https';

// Start writing Firebase Functions
// https://firebase.google.com/docs/functions/typescript

admin.initializeApp(functions.config().firebase);

export class Question {
  public course: number;
  public year: number;
  public moed: string;
  public semester: string;
  public photo: string;
  public number: number;
  public total_grade: number;
}

export class QuestionId extends  Question {
  public id: string;
}

export class Solution {
  public photo: string;
  public grade: number;
}

export class Course {
  public id: number;
  public name: string;
  public faculty: string;
}

function capStr(str: string): string {
  return str.charAt(0).toUpperCase() + str.slice(1);
}

async function addSolImage(pdf: PDFDocument, url, x ,y){
  return new Promise(async(resolve, reject) => {
    const req = await https.get(url, (res) => {
      res.setEncoding('base64');
      let body = "data:" + res.headers["content-type"] + ";base64,";
      res.on('data', (d) => {
        body += d;
      });
      res.on('end', () => {
        pdf.image(body, { width: 500, align: 'center' });
        resolve(res);
      });
    });
    req.on('error', err => {
      console.error('error!');
      reject(err);
    });

  });

}

async function getBestSolutionFor(q: QuestionId): Promise<Solution> {
  const query = admin.firestore().collection(`questions/${q.id}/solutions`).orderBy('grade', 'desc').limit(1);
  return query.get().then(res => res.docs[0].data() as Solution);
}

async function addQuestion(pdf: PDFDocument, q: QuestionId) {
  pdf.addPage();
  const sol = await getBestSolutionFor(q);
  pdf.fontSize(25).text(`Question ${q.number} (${sol.grade}/${q.total_grade})`, 50, 50);
  pdf.moveDown();
  await addSolImage(pdf, sol.photo, 0, 80);
}

async function getQuestionsOfExam(course: number, year: number, semester: string, moed: string): Promise<QuestionId[]> {
  return admin.firestore().collection('questions')
    .where('course', '==', course)
    .where('year', '==', year)
    .where('semester', '==', semester)
    .where('moed', '==', moed)
    .orderBy('number')
    .get().then(docs => {
    return docs.docs.map(snap => {
      return {id: snap.id, ...snap.data() as Question};
    });
  });
}

async function getCourse(course: number): Promise<Course> {
  return admin.firestore().collection('courses').doc(course.toString()).get().then(doc => doc.data() as Course);
}

export const getPDFofExam = functions.https.onRequest(async (request, response) => {

  const course = +request.query.course;
  const year = +request.query.year;
  const semester = request.query.semester;
  const moed = request.query.moed;

  if (!course || !year || !semester || !moed) return;

  const courseData = await getCourse(course);

  const questions = await getQuestionsOfExam(course, year, semester, moed);

  console.log(`Found ${questions.length} questions for ${course}, ${year}, ${semester}, ${moed}`);

  const pdf = new PDFDocument;

  pdf.pipe(response);

  pdf.fontSize(30).text(`${courseData.id} ${courseData.name}`, { align: 'center' });
  pdf.moveDown(2);
  pdf.fontSize(26).text(`${capStr(semester)} ${year}`, { align: 'center' });
  pdf.moveDown();
  pdf.fontSize(26).text(`Moed ${moed}`, { align: 'center' });
  pdf.moveDown(5);
  pdf.fontSize(20).text('Automatically Generated by Testock', { align: 'center', link: 'http://www.testock.com', underline: true })

  for (const q of questions) {

    await addQuestion(pdf, q);

  }

  pdf.end();

});
